from django.urls import path
from . import views
from django.contrib.auth import views as auth_views


urlpatterns = [
    path('', auth_views.LoginView.as_view(redirect_authenticated_user=True), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('tyre/', views.TyreView.as_view(), name='tyre'),
    path('filter-tyre/<str:brand>/', views.FilterTyreView.as_view(), name='filter-tyre'),
    path('setting/', views.SettingView.as_view(), name='setting'),
    path('address/', views.AddressView.as_view(), name='address'),
    path('delete-address/<int:id>/', views.DeleteAddressView.as_view(), name='delete-address'),
    path('update-address/<int:id>/', views.UpdateAddressView.as_view(), name='update-address'),
    path('change-password/', views.ChangePasswordView.as_view(), name='change-password'),
    path('search-result/', views.SearchResultView.as_view(), name='search-result'),
    path('tyre-detail/<int:id>/', views.TyreDetailView.as_view(), name='tyre-detail'),
    path('cart/', views.CartView.as_view(), name='cart'),
    path('delete-item/<int:id>/', views.DeleteItemView.as_view(), name='delete-item'),
    path('my-order/', views.MyOrderView.as_view(), name='my-order'),
    path('add-to-cart/<int:id>/', views.AddToCartView.as_view(), name='add-to-cart'),
    path('cart-value/<int:id>/', views.CartValueView.as_view(), name='cart-value'),
    path('add-to-my-order/', views.AddToMyOrderView.as_view(), name='add-to-my-order'),
    path('confirm-order/', views.ConfirmOrderView.as_view(), name='confirm-order'),
    path('invoice/<int:id>/', views.InvoiceView.as_view(), name='invoice'),
    path('invoice-pdf/<int:id>/', views.generate_invoice_pdf, name='invoice-pdf'),
    path('notifications/', views.NotificationsView.as_view(), name='notifications'),
    path('delete-notification/<int:id>/', views.DeleteNotificationView.as_view(), name='delete-notification'),
    path('privacy-policies/', views.PrivacyPolicyView.as_view(), name='privacy-policies'),
    path('terms-and-conditions/', views.TermsAndConditionsView.as_view(), name='terms-and-conditions'),
    path('dashboard/admin/', views.Dasboard.as_view(), name='dashboard'),
    path('retailer-detail/admin/<int:id>/', views.RetailerDetails.as_view(), name='retailer-detail'),
    path('pending-orders/admin/<int:id>/', views.PendingOrders.as_view(), name='pending-orders'),
    path('total-orders/admin/<int:id>/', views.TotalOrderView.as_view(), name='total-orders'),
    path('user-invoice/admin/<int:id>/', views.UserInvoiceView.as_view(), name='user-invoice'),
    path('user-invoice-pdf/admin/<int:id>/', views.generate_user_invoice_pdf, name='user-invoice-pdf'),
    path('price-reports/admin/', views.PriceReportsView.as_view(), name='price-reports'),
    path('price-reports-pdf/admin/', views.generate_reports_pdf, name='price-reports-pdf'),
    path('retailer-reports/admin/', views.RetailerReportsView.as_view(), name='retailer-reports'),
    path('retailers-reports-pdf/admin/', views.generate_retailers_reports_pdf, name='retailers-reports-pdf'),
    path('top-search-reports/admin/', views.SearchReportsView.as_view(), name='top-search-reports'),
    path('top-search-reports-pdf/admin/', views.generate_top_search_reports_pdf, name='top-search-reports-pdf'),
    path('orders/admin/', views.OrdersView.as_view(), name='orders'),
    path('order-update/admin/<int:id>/', views.UpdateOrderView.as_view(), name='order-update'),
    path('order-delete-confirm/admin/<int:id>/', views.ConfirmDeleteOrderView.as_view(), name='order-delete-confirm'),
    path('order-delete/admin/<int:id>/', views.DeleteOrderView.as_view(), name='order-delete'),
    path('upload-stock-xlsx/admin/', views.UploadStockXLSXView.as_view(), name='upload-stock-xlsx'),
    path('upload-xlsx/admin/', views.UploadXLSXView.as_view(), name='upload-xlsx'),
]